application: zippyzipjp2
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /
  script: main.py
  
- url: /(fetch|kick)
  script: \1.py
  login: admin

builtins:
- datastore_admin: on
